Repository innerstella/itsBasic, pull requests merged in 2024-03, with the labels that each got.

#37 WHITE 1주차 개발 내용
  .gitignore
  build/asset-manifest.json
  build/assets/fonts/Pretendard-Bold.woff
  build/assets/fonts/Pretendard-Regular.woff
  build/assets/link/blue.svg
  build/assets/link/green.svg
  build/assets/link/orange.svg
  build/assets/link/purple.svg
  build/index.html
  build/static/css/main.ddc79a2b.css
  build/static/css/main.ddc79a2b.css.map
  build/static/css/main.f855e6bc.css
  build/static/css/main.f855e6bc.css.map
  build/static/js/main.56decfc7.js
  build/static/js/main.56decfc7.js.map
  build/static/js/main.803c3e72.js
  build/static/js/main.803c3e72.js.LICENSE.txt
  build/static/js/main.803c3e72.js.map
  build/static/media/Pretendard-Bold.1f1dbbbf311ffffcc770.woff
  build/static/media/Pretendard-Regular.303253288b0ba99db532.woff
  public/assets/.gitkeep
  public/assets/common/logo_icon.svg
  public/assets/link/arrow-left.svg
  public/assets/link/arrow-right.svg
  public/assets/link/blue.svg
  public/assets/link/empty.svg
  public/assets/link/green.svg
  public/assets/link/orange.svg
  public/assets/link/purple.svg
  public/assets/main/service_card_image.png
  public/assets/main/service_image_card1.png
  public/assets/main/service_image_card2.png
  public/assets/main/service_image_card3.png
  public/assets/main/service_image_emoji.png
  src/components/button/Button.jsx
  src/components/button/Button.styles.js
  src/components/navigationBar/NavigationBar.jsx
  src/components/navigationBar/NavigationBar.styles.js
  src/pages/list/ListPage.style.js
  src/pages/list/components/ArrowBtn/ArrowBtn.jsx
  src/pages/list/components/ArrowBtn/ArrowBtn.style.js
  src/pages/list/components/Card/Card.jsx
  src/pages/list/components/Card/Card.style.js
  src/pages/list/components/CardList/CardList.jsx
  src/pages/list/components/CardList/CardList.style.js
  src/pages/list/data/dummy.json
  src/pages/list/index.jsx
  src/pages/main/MainPage.styles.js
  src/pages/main/index.jsx
Labels: WHITE

#38 Post 작성 페이지, 반응형, 하단 버튼 반응형 수정
  public/assets/post-to/Enabled.svg
  src/Router.js
  src/components/button/Button.jsx
  src/components/button/Button.styles.js
  src/pages/post-to/PostToPage.styles.js
  src/pages/post-to/components/Card.jsx
  src/pages/post-to/components/Card.styles.js
  src/pages/post-to/index.jsx
Labels: WHITE

#49 [POST]#44 Emoji 등록 기능, 메시지 모달 연동, 기타 버그 수정.
  src/pages/post/components/HeaderAddEmojiButton/HeaderAddEmojiButton.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.style.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.style.jsx
  src/pages/post/components/postCard/PostCardItem.jsx
  src/pages/post/components/postCard/PostCardStyle.jsx
  src/pages/post/components/postCard/api.js
Labels: POST

#51 /post/{id}/message UI 구현
  package-lock.json
  package.json
  public/assets/post-to/person.svg
  public/index.html
  src/Router.js
  src/pages/list/ListPage.style.jsx
  src/pages/list/components/ArrowBtn/ArrowBtn.style.jsx
  src/pages/list/components/Card/Card.style.jsx
  src/pages/list/components/CardList/CardList.style.jsx
  src/pages/list/data/dummy.json
  src/pages/list/index.jsx
  src/pages/post-to/PostMessagePage.jsx
  src/pages/post-to/PostMessagePage.style.jsx
  src/pages/post-to/components/dropdown/Dropdown.jsx
  src/pages/post-to/components/dropdown/Dropdown.style.jsx
  src/pages/post-to/components/profile/Profile.style.jsx
  src/pages/post-to/components/profile/Proifle.jsx
  src/pages/post-to/components/text-editor/TextEditor.jsx
Labels: WHITE

#52 fix - 무한 스크롤 버그 수정
  src/pages/post/components/postCard/PostCardItem.jsx
  src/pages/post/components/postCard/api.js
Labels: FIX

#54 Emoji 관련 기능 완성 및 유효하지 않은 페이지 이동시 버그 수정#44
  src/pages/post/components/HeaderAddEmojiButton/HeaderAddEmojiButton.jsx
  src/pages/post/components/HeaderButtonBox/HeaderButtonBox.jsx
  src/pages/post/components/HeaderServiceBox/HeaderServiceBox.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.style.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.jsx
  src/pages/post/components/Utils/handleEmojiSelect.js
  src/utils/callToastNotify.js
Labels: FIX, FEATURE, REFACTOR

#58 [Post] URL 공유 버튼 클릭시 Toastify 알람기능 추가
  src/pages/post/components/ShareDropdownModal/ShareDropdownModal.jsx
  src/pages/post/components/WriterImageBox/WriterImageBox.jsx
Labels: FEATURE

#59 휴지통으로 삭제 후 edit에 남아있게 변경
  src/components/PostCard.jsx
  src/pages/post/components/PostPageMain/PostPageMain.jsx
  src/pages/post/components/postCard/DeleteButton.jsx
  src/pages/post/components/postCard/PostCardAdd.jsx
  src/pages/post/components/postCard/PostCardItem.jsx
  src/pages/post/components/postCard/PostCardItem.style.jsx
Labels: POST

#61 ✨ 프로필 이미지 선택 기능
  src/pages/post-to/components/profile/Profile.style.jsx
  src/pages/post-to/components/profile/Proifle.jsx
Labels: FEATURE

#63 Post 게시글 배경 정보를 서버에서 받아오게 함 및 일부 리팩토링 #44
  src/pages/post/components/HeaderAddEmojiButton/HeaderAddEmojiButton.jsx
  src/pages/post/components/HeaderFeatureBox/HeaderFeatureBox.jsx
  src/pages/post/components/HeaderFeatureBox/HeaderFeatureBox.style.jsx
  src/pages/post/components/HeaderLogoBox/HeaderLogoBox.jsx
  src/pages/post/components/HeaderLogoBox/HeaderLogoBox.style.jsx
  src/pages/post/components/HeaderServiceBox/HeaderServiceBox.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.style.jsx
  src/pages/post/components/PostPageMain/PostPageMain.jsx
  src/pages/post/components/PostPageMain/PostPageMain.style.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.style.jsx
  src/pages/post/components/Utils/handleEmojiSelect.js
  src/pages/post/components/postCard/PostCardItem.jsx
  src/utils/callToastNotify.js
Labels: FEATURE, REFACTOR

#64 🐛 게시물을 삭제했을때 무한스크롤이 제대로 작동하지 않는 버그 수정
  src/pages/post/components/postCard/PostCardItem.jsx
Labels: FIX

#65 POST To 페이지 기능 구현
  src/components/button/Button.jsx
  src/components/button/Button.style.jsx
  src/components/navigationBar/NavigationBar.jsx
  src/components/navigationBar/NavigationBar.style.jsx
  src/pages/main/MainPage.style.jsx
  src/pages/main/index.jsx
  src/pages/post-to/PostToPage.style.jsx
  src/pages/post-to/components/Card.jsx
  src/pages/post-to/components/Card.style.jsx
  src/pages/post-to/components/Card.styles.js
  src/pages/post-to/index.jsx
Labels: FEATURE

#77 🐛 메인페이지에서 이모지 목록 보여줄때 한번 추가하고 뺀 이모티콘 개수가 0개로 보이는 버그
  src/pages/list/components/Card/Card.jsx
Labels: FIX

#81 🐛 상단 오버스크롤 관련 문제 픽스? #79
  src/pages/post/index.jsx
  src/pages/post/index.style.jsx
Labels: REFACTOR

#80 postTo 페이지 스켈레톤 UI, 주석 추가
  src/components/button/Button.jsx
  src/components/navigationBar/NavigationBar.jsx
  src/components/navigationBar/NavigationBar.style.jsx
  src/pages/main/index.jsx
  src/pages/post-to/components/Card.jsx
  src/pages/post-to/components/post-to-card/Card.jsx
  src/pages/post-to/components/post-to-card/Card.style.jsx
  src/pages/post-to/components/post-to-card/SkeletonUI.jsx
  src/pages/post-to/components/post-to-card/SkeletonUI.style.jsx
  src/pages/post-to/index.jsx
Labels: UI

#87 [post-to] 포켓몬 API를 통한 프로필 이미지 선택 모달창 개발
  public/assets/post-to/poke_ball_icon.png
  public/index.html
  src/pages/list/components/CardList/CardList.style.jsx
  src/pages/post-to/PostMessagePage.jsx
  src/pages/post-to/components/profile/PokemonProfileModal.jsx
  src/pages/post-to/components/profile/PokemonProfileModal.style.jsx
  src/pages/post-to/components/profile/Profile.style.jsx
  src/pages/post-to/components/profile/Proifle.jsx
Labels: FEATURE, UI

#93 [post-to] 이미지 인라인 스타일 제거, 코드 리팩토링
  src/pages/post-to/components/post-to-card/Card.style.jsx
  src/pages/post-to/components/post-to-card/CardList.jsx
  src/pages/post-to/components/post-to-card/ImageCard.jsx
  src/pages/post-to/components/post-to-card/SkeletonUI.jsx
  src/pages/post-to/components/post-to-card/SkeletonUI.style.jsx
  src/pages/post-to/index.jsx
Labels: REFACTOR

#101 [Post-to]포켓몬 프로필 모달 완성
  src/pages/post-to/components/profile/PokemonModalLoading.jsx
  src/pages/post-to/components/profile/PokemonModalLoading.style.jsx
  src/pages/post-to/components/profile/PokemonProfileModal.jsx
  src/pages/post-to/components/profile/Profile.style.jsx
  src/pages/post-to/components/profile/Proifle.jsx
Labels: FEATURE, UI

#102 [Post] 코드 리팩토링 및 에러 제거, 마이너한 ui feature
  src/components/PrimaryButton.jsx
  src/components/PrimaryButton40.jsx
  src/components/PrimaryButton56.jsx
  src/pages/post/components/HeaderAddEmojiButton/HeaderAddEmojiButton.style.jsx
  src/pages/post/components/HeaderShareButton/HeaderShareButton.style.jsx
  src/pages/post/components/HeaderToolBar/HeaderToolBar.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.style.jsx
  src/pages/post/components/PostPageMain/PostPageMain.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.style.jsx
  src/pages/post/components/Utils/API.js
  src/pages/post/components/WriterImageBox/WriterImageBox.jsx
  src/pages/post/components/WriterImageBox/WriterImageBox.style.jsx
  src/pages/post/components/postCard/DeleteButton.jsx
  src/pages/post/components/postCard/PostCardAdd.jsx
  src/pages/post/components/postCard/PostCardItem.jsx
  src/pages/post/components/postCard/PostCardItem.style.jsx
  src/pages/post/components/postCard/api.js
  src/pages/post/index.jsx
Labels: FIX, REFACTOR

#103 [list, post/{id}/message] 커서 포인터 추가
  src/pages/.gitkeep
  src/pages/list/components/Card/Card.style.jsx
  src/pages/post-to/PostMessagePage.jsx
  src/pages/post-to/components/dropdown/Dropdown.jsx
  src/pages/post-to/components/dropdown/Dropdown.style.jsx
  src/pages/post-to/components/profile/Profile.jsx
  src/pages/post-to/components/profile/Profile.style.jsx
  src/pages/post-to/components/wide-button/WideButton.style.jsx
Labels: FIX

#106 [Post] 카카오톡 연동 수정
  src/GlobalStyles.js
  src/Router.js
  src/components/navigationBar/NavigationBar.jsx
  src/components/navigationBar/NavigationBar.style.jsx
  src/context/themeProvider.js
  src/pages/post/components/ShareDropdownModal/ShareDropdownModal.jsx
  src/theme/ThemeToggle.jsx
  src/theme/theme.js
  src/utils/shareKakao.js
Labels: FIX

#111 [파일 관리] 배포 관련 파일 제외
  .firebase/hosting.YnVpbGQ.cache
  .gitignore
  build/asset-manifest.json
  build/assets/fonts/Pretendard-Bold.woff
  build/assets/fonts/Pretendard-Regular.woff
  build/assets/link/blue.svg
  build/assets/link/green.svg
  build/assets/link/orange.svg
  build/assets/link/purple.svg
  build/favicon.ico
  build/index.html
  build/logo192.png
  build/logo512.png
  build/manifest.json
  build/robots.txt
  build/static/css/main.ddc79a2b.css
  build/static/css/main.ddc79a2b.css.map
  build/static/js/main.803c3e72.js
  build/static/js/main.803c3e72.js.LICENSE.txt
  build/static/js/main.803c3e72.js.map
  build/static/media/Pretendard-Bold.1f1dbbbf311ffffcc770.woff
  build/static/media/Pretendard-Regular.303253288b0ba99db532.woff
Labels: DEPLOY

#107 [Post, ReadMe] 리드미 간략한 완성 및 Post 페이지 일부 리팩토링
  README.md
  src/pages/post/components/DropdownClickCancel/DropdownClickCancel.jsx
  src/pages/post/components/HeaderAddEmojiButton/HeaderAddEmojiButton.jsx
  src/pages/post/components/HeaderFeatureBox/HeaderFeatureBox.jsx
  src/pages/post/components/HeaderFeatureBox/HeaderFeatureBox.style.jsx
  src/pages/post/components/HeaderLogoBox/HeaderLogoBox.jsx
  src/pages/post/components/HeaderLogoBox/HeaderLogoBox.style.jsx
  src/pages/post/components/HeaderShareButton/HeaderShareButton.jsx
  src/pages/post/components/HeaderShareButton/HeaderShareButton.style.jsx
  src/pages/post/components/HeaderToolBar/HeaderToolBar.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.style.jsx
  src/pages/post/components/ShareDropdownModal/ShareDropdownModal.jsx
  src/pages/post/components/ShareDropdownModal/ShareDropdownModal.style.jsx
  src/pages/post/components/postCard/DeleteButton.jsx
  src/pages/post/components/postCard/DeleteButton.style.jsx
  src/pages/post/components/postCard/PostCardItem.jsx
  src/pages/post/components/postCard/PostCardItem.style.jsx
  src/pages/post/components/postCard/TrashButton.jsx
  src/pages/post/index.jsx
  src/pages/post/index.style.jsx
Labels: FIX, DOCS, REFACTOR

#115 [post,list] 다크모드 적용
  src/Router.js
  src/components/navigationBar/NavigationBar.jsx
  src/components/navigationBar/NavigationBar.style.jsx
  src/context/themeProvider.js
  src/pages/main/MainPage.style.jsx
  src/pages/main/index.jsx
  src/pages/post-to/components/profile/Profile.jsx
  src/pages/post-to/components/profile/Profile.style.jsx
  src/pages/post/components/HeaderFeatureBox/HeaderFeatureBox.style.jsx
  src/pages/post/components/MessageRecipient/MessageRecipient.style.jsx
  src/pages/post/components/MessageWriterBox/MessageWriterBox.style.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.style.jsx
  src/pages/post/components/WriterImageBox/WriterImageBox.style.jsx
  src/pages/post/components/postCard/PostCardItem.style.jsx
  src/pages/post/index.jsx
  src/theme/ThemeToggle.jsx
  src/theme/theme.js
Labels: FEATURE

#122 [Post, Post-to, main] 포켓몬 모달 성능 개선 및 각 페이지마다 세부 스타일 수정
  src/Router.js
  src/components/navigationBar/NavigationBar.style.jsx
  src/pages/list/ListPage.style.jsx
  src/pages/list/components/Card/Card.jsx
  src/pages/list/components/Card/Card.style.jsx
  src/pages/post-to/components/profile/PokemonModalLoading.style.jsx
  src/pages/post-to/components/profile/PokemonProfileModal.jsx
  src/pages/post-to/components/profile/PokemonProfileModal.style.jsx
  src/pages/post-to/components/profile/Profile.jsx
  src/pages/post-to/index.jsx
  src/pages/post/components/DropdownClickCancel/DropdownClickCancel.jsx
  src/pages/post/components/HeaderAddEmojiButton/HeaderAddEmojiButton.style.jsx
  src/pages/post/components/HeaderFeatureBox/HeaderFeatureBox.jsx
  src/pages/post/components/HeaderFeatureBox/HeaderFeatureBox.style.jsx
  src/pages/post/components/HeaderShareButton/HeaderShareButton.jsx
  src/pages/post/components/HeaderShareButton/HeaderShareButton.style.jsx
  src/pages/post/components/ShareDropdownModal/ShareDropdownModal.jsx
  src/pages/post/components/WriterImageBox/WriterImageBox.jsx
  src/pages/post/components/WriterImageBox/WriterImageBox.style.jsx
Labels: REFACTOR, UI

#116 [post-to] SEO 및 성능 개선, 엔터 키로 메시지 등록
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  docs/pull_request_template.md
  firebase.json
  public/assets/.gitkeep
  src/components/button/Button.jsx
  src/components/button/Button.style.jsx
  src/pages/post-to/PostMessagePage.jsx
  src/pages/post-to/components/dropdown/Dropdown.jsx
  src/pages/post-to/components/profile/Profile.jsx
  src/pages/post-to/components/text-editor/TextEditor.jsx
  src/pages/post-to/components/text-input/TextInput.jsx
  src/pages/post-to/components/wide-button/WideButton.jsx
  src/pages/post-to/index.jsx
Labels: FIX, OPT/ACCESS

#108 [main] SEO 및 성능 개선
  public/assets/main/service_card_image.png
  public/assets/main/service_card_image.webp
  public/assets/main/service_image_card1.png
  public/assets/main/service_image_card2.png
  public/assets/main/service_image_card3.png
  public/assets/main/service_image_emoji.png
  public/assets/main/service_image_emoji.webp
  src/components/navigationBar/NavigationBar.jsx
  src/components/navigationBar/NavigationBar.style.jsx
  src/fonts.css
  src/pages/main/MainPage.style.jsx
  src/pages/main/index.jsx
Labels: OPT/ACCESS

#127 [List, Message] 세부 스타일링 설정
  src/pages/list/components/ArrowBtn/ArrowBtn.style.jsx
  src/pages/post-to/components/profile/PokemonProfileModal.jsx
  src/pages/post-to/components/profile/PokemonProfileModal.style.jsx
  src/pages/post-to/components/profile/Profile.style.jsx
Labels: UI

#126 [Readme, Post, Post-To, List] 프로젝트 제목 최신화 및 태그 조정, 작성자만 삭제 기능 및 기타 styled-component 에러 제거
  README.md
  src/components/navigationBar/NavigationBar.jsx
  src/components/navigationBar/NavigationBar.style.jsx
  src/pages/list/ListPage.style.jsx
  src/pages/list/components/CardList/CardList.jsx
  src/pages/list/components/CardList/CardList.style.jsx
  src/pages/list/index.jsx
  src/pages/post-to/PostMessagePage.jsx
  src/pages/post-to/index.jsx
  src/pages/post/components/DropdownClickCancel/DropdownClickCancel.jsx
  src/pages/post/components/HeaderShareButton/HeaderShareButton.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.style.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.style.jsx
  src/pages/post/components/ShareDropdownModal/ShareDropdownModal.jsx
  src/pages/post/components/WriterImageBox/WriterImageBox.jsx
  src/pages/post/components/postCard/CardRelationship.jsx
  src/pages/post/components/postCard/DeleteButton.jsx
  src/pages/post/components/postCard/PostCardItem.jsx
  src/pages/post/components/postCard/PostCardItem.style.jsx
  src/pages/post/index.jsx
Labels: FIX, DOCS, REFACTOR, UI

#128 [post, post-to, main] 공용 버튼 컴포넌트 호버, 액티브, 포커스 상태 스타일링 및 세부 스타일링
  src/components/button/Button.style.jsx
  src/components/navigationBar/NavigationBar.style.jsx
  src/pages/list/ListPage.style.jsx
  src/pages/list/index.jsx
  src/pages/post-to/PostToPage.style.jsx
  src/pages/post-to/components/post-to-card/Card.style.jsx
  src/pages/post/components/postCard/DeleteButton.style.jsx
Labels: UI

#131 [post, list] 버튼 , 포켓몬 모달 세부 스타일링 조정
  src/components/button/Button.style.jsx
  src/pages/list/ListPage.style.jsx
  src/pages/list/index.jsx
  src/pages/main/MainPage.style.jsx
  src/pages/main/index.jsx
  src/pages/post-to/components/profile/PokemonProfileModal.jsx
  src/pages/post-to/components/profile/Profile.jsx
  src/pages/post-to/components/profile/Profile.style.jsx
  src/pages/post/components/HeaderShareButton/HeaderShareButton.jsx
Labels: UI

#134 [post-to] 포켓몬 모달 작동 UI 변경 및 모바일 사이즈 스타일링
  src/pages/post-to/components/profile/PokemonModalLoading.style.jsx
  src/pages/post-to/components/profile/PokemonProfileModal.jsx
  src/pages/post-to/components/profile/PokemonProfileModal.style.jsx
Labels: REFACTOR, UI

#136 [Post]💄 Post 페이지 헤더부분 깨지는 현상 해결, 헤더부분 드롭다운 아이콘 다크모드에 맞춰 색상 변경 적용
  src/pages/post/components/HeaderAddEmojiButton/HeaderAddEmojiButton.jsx
  src/pages/post/components/HeaderToolBar/HeaderToolBar.style.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.style.jsx
  src/pages/post/components/PostPageMain/PostPageMain.jsx
  src/pages/post/index.jsx
  src/pages/post/index.style.jsx
  src/theme/ThemeToggle.jsx
Labels: REFACTOR, UI

#135 [list] tablet, mobile 스크롤 해결 및 전체 데이터에 대해 정렬
  src/pages/list/ListPage.style.jsx
  src/pages/list/components/Card/Card.jsx
  src/pages/list/components/CardList/CardList.jsx
  src/pages/list/components/EmptyCard/EmptyCard.jsx
  src/pages/list/index.jsx
Labels: FIX

#138 [전체] ui fix
  package-lock.json
  package.json
  public/assets/common/moon.svg
  public/assets/common/sun.svg
  src/Router.js
  src/components/navigationBar/NavigationBar.style.jsx
  src/components/skeleton/SkeletonNew.jsx
  src/fonts.css
  src/pages/list/components/Card/Card.jsx
  src/pages/list/components/Card/Card.style.jsx
  src/pages/list/components/CardList/CardList.jsx
  src/pages/main/index.jsx
  src/pages/post/components/WriterImageBox/WriterImageBox.style.jsx
  src/theme/ThemeToggle.jsx
Labels: UI

#140 ⏪ 프로필 겹치게 하기
  src/pages/list/components/Card/Card.style.jsx
  src/pages/post/components/WriterImageBox/WriterImageBox.style.jsx
Labels: DEPLOY

#142 [Readme] 변경된 타이틀에 맞춰 일부 이미지 수정
  README.md
Labels: DOCS

#141 [main]💄 메인페이지 두번째 이미지 모바일에서 비율 안맞는 문제 해결
  src/pages/main/MainPage.style.jsx
  src/pages/main/index.jsx
Labels: UI

#143 Develop
  README.md
  src/pages/main/MainPage.style.jsx
  src/pages/main/index.jsx
Labels: DEPLOY

#144 [post, profile] 스켈레톤 적용
  src/components/skeleton-ui/SkeletonUI.jsx
  src/components/skeleton-ui/SkeletonUI.style.jsx
  src/pages/list/ListPage.style.jsx
  src/pages/list/components/CardList/CardList.style.jsx
  src/pages/post-to/components/post-to-card/ImageCard.jsx
  src/pages/post-to/components/post-to-card/SkeletonUI.jsx
  src/pages/post-to/components/profile/Profile.jsx
  src/pages/post-to/components/profile/Profile.style.jsx
  src/pages/post/components/HeaderFeatureBox/HeaderFeatureBox.jsx
  src/pages/post/components/HeaderToolBar/HeaderToolBar.jsx
  src/pages/post/components/MessageRecipient/MessageRecipient.jsx
  src/pages/post/components/MessageRecipient/MessageRecipient.style.jsx
  src/pages/post/components/MessageWriterBox/MessageWriterBox.jsx
  src/pages/post/components/MessageWriterBox/MessageWriterBox.style.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.jsx
  src/pages/post/components/PostPageMain/PostPageMain.jsx
  src/pages/post/components/PostPageMain/PostPageMain.style.jsx
  src/pages/post/components/postCard/PostCardItem.jsx
  src/pages/post/index.jsx
Labels: FEATURE

#145 merge - [post, profile] 스켈레톤 적용
  src/components/skeleton-ui/SkeletonUI.jsx
  src/components/skeleton-ui/SkeletonUI.style.jsx
  src/pages/list/ListPage.style.jsx
  src/pages/list/components/CardList/CardList.style.jsx
  src/pages/post-to/components/post-to-card/ImageCard.jsx
  src/pages/post-to/components/post-to-card/SkeletonUI.jsx
  src/pages/post-to/components/profile/Profile.jsx
  src/pages/post-to/components/profile/Profile.style.jsx
  src/pages/post/components/HeaderFeatureBox/HeaderFeatureBox.jsx
  src/pages/post/components/HeaderToolBar/HeaderToolBar.jsx
  src/pages/post/components/MessageRecipient/MessageRecipient.jsx
  src/pages/post/components/MessageRecipient/MessageRecipient.style.jsx
  src/pages/post/components/MessageWriterBox/MessageWriterBox.jsx
  src/pages/post/components/MessageWriterBox/MessageWriterBox.style.jsx
  src/pages/post/components/MostEmojiBox/MostEmojiBox.jsx
  src/pages/post/components/PostPageMain/PostPageMain.jsx
  src/pages/post/components/PostPageMain/PostPageMain.style.jsx
  src/pages/post/components/postCard/PostCardItem.jsx
  src/pages/post/index.jsx
Labels: DEPLOY

#147 🐛 다른 페이지에서 동일 이모지 증감 상태를 공유하는 문제 해결
  src/pages/post/components/Utils/handleEmojiSelect.js
Labels: FIX

#149 [Post-to]💄 PostMessagePage 모바일 사이즈 스타일링
  src/Router.js
  src/pages/post-to/PostMessagePage.jsx
  src/pages/post-to/PostMessagePage.style.jsx
  src/pages/post-to/components/profile/Profile.style.jsx
Labels: UI

#151 💄 모바일 사이즈 깨지는 부분만 수정
  src/pages/post-to/components/profile/PokemonProfileModal.style.jsx
  src/pages/post/components/RollingMessageModal/RollingMessageModal.style.jsx
Labels: UI
